import { PATIENTS } from '../actions/patients';

const defaultState = {
  // fake data
  // eslint-disable-all-line
  loaded: false,
  loading: false,
  Patients: [
    {
      FullName: ' Morgan fat7e',
      MobilePhone: '01115154723',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PATb9afd6283610e810',
      Gender: false,
      BirthDate: '2016-11-07T00:00:00',
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 0,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'AAAAAAAA',
      MobilePhone: '01001393442',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT203cbbbc54e999b7',
      Gender: false,
      BirthDate: null,
      Identifier: '',
      InsuranceProviderKey: 'ins68a92',
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: {
        InsuranceProviderId: 2,
        Name: 'Bupa Egypt Insurance',
        NameArabic: 'شركة بوبا للتأمين',
        DisplayOrder: 0,
        InsuranceKey: 'ins68a92',
      },
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'abd alhamed (lybia)',
      MobilePhone: '1024274697',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT269d43fa96fbe400',
      Gender: false,
      BirthDate: null,
      Identifier: '',
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'abd alhamed (lybia)',
      MobilePhone: '01024274697',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT4ff59f9f30fa3550',
      Gender: false,
      BirthDate: '2017-02-22T00:00:00',
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 8,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abdallah Mohamed',
      MobilePhone: '01096323245',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT2f65f078565868a0',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abdel Aziz Elshazly',
      MobilePhone: '01064503096',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT8c1bcd45e58f4720',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abdel Wahab Ehab',
      MobilePhone: '01003887782',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT5658164136390110',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 8,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abdel Wedood Hani',
      MobilePhone: '01007569764',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT851b6d304f95cd70',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abdelaziz American Pt',
      MobilePhone: '01280739831',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT3cb2b3e5f2b7cce0',
      Gender: false,
      BirthDate: '2016-11-03T00:00:00',
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 0,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abdul Malik ',
      MobilePhone: '01001247623',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT9d1b99f591a93670',
      Gender: false,
      BirthDate: '2016-02-24T00:00:00',
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 8,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abdulla khodary',
      MobilePhone: '01002132322',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PATa03ed93196d7f7e0',
      Gender: false,
      BirthDate: '2015-11-30T00:00:00',
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 0,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abeer',
      MobilePhone: '01120399833',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT257c334d056d6c61',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abeer Atef Ahmed',
      MobilePhone: '01017826927',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PATd5e9056246504da0',
      Gender: true,
      BirthDate: '2015-05-28T00:00:00',
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 8,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abeer El Dawy',
      MobilePhone: '01001662525',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT787261d1dda1a9c0',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Abla Fawzy',
      MobilePhone: '01023381121',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT2a3ab6b0b27e72d0',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Ahmed alazazy',
      MobilePhone: '01007770178',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT10da6e7f54edc490',
      Gender: false,
      BirthDate: '2017-04-18T00:00:00',
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 0,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Ahmed Ali',
      MobilePhone: '01006070452',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT627106ee0e9b5a70',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Ahmed Khalifa ',
      MobilePhone: '01001711237',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PAT6cb50b4341e5aee0',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
    {
      FullName: 'Ahmed Mohamed Abdel Gwad',
      MobilePhone: '01222174770',
      CountryCode: '+20',
      Address: null,
      PatientKey: 'PATc6bcd8ce0d0d6080',
      Gender: false,
      BirthDate: null,
      Identifier: null,
      InsuranceProviderKey: null,
      HomeNumber: null,
      Notes: null,
      RelativeName: null,
      PatientRelativeId: 1,
      EmailAddress: null,
      CountryIsoCode: 'EG',
      InsuranceProvider: null,
      IsDeleted: null,
      PatientId: 0,
      InsuranceProviderId: null,
    },
  ],
  textForSearch: '',
};

export default (state = defaultState, { type, ...action }) => {
  let patientsObj = [];
  if (action.patients && action.patients.data && action.patients.data.Patients) {
    patientsObj = action.patients.data.Patients;
  }
  switch (type) {
  case PATIENTS.LOAD:
    return Object.assign({}, state, { loaded: false }, { loading: true });
  case PATIENTS.LOAD_DONE:
    return Object.assign({}, state, patientsObj, { loaded: false }, { loading: true });
  // case PATIENTS.CHANGE_TEXT_FOR_SEARCH:
  //   return Object.assign({}, state, { textForSearch: action.textForSearch });
  default:
    return state;
  }
};
